Repository AY2425S2-CS2103T-F11-4/tp, pull requests merged in 2025-03, with the labels that each got.

#26 Update README.md with WantedList details
  README.md
  docs/images/Ui.png
Labels: type.Documentation

#29 Update project name Wanted in the top navigation bar and home page
  docs/index.md
Labels: type.Documentation

#31 Update product scope
  docs/DeveloperGuide.md
Labels: type.Documentation

#42 Fix test cases failed due to filepath issues from refactoring
  src/test/data/JsonLoanBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonLoanBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonLoanBookStorageTest/notJsonFormatAddressBook.json
  src/test/data/JsonSerializableLoanBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableLoanBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableLoanBookTest/typicalPersonsAddressBook.json
  src/test/resources/view/UiPartTest/validFileWithFxRoot.fxml
Labels: type.Bug, priority.High, severity.High

#50 Update list of features in README.md
  README.md
Labels: type.Documentation, priority.Low

#59 Add Repay Command
  src/main/java/wanted/logic/commands/RepayCommand.java
  src/main/java/wanted/logic/parser/AddressBookParser.java
  src/main/java/wanted/logic/parser/RepayCommandParser.java
  src/test/java/wanted/logic/commands/RepayCommandTest.java
Labels: type.Task, priority.High

#57 Modify LoanListCard in UI
  src/main/java/wanted/ui/LoanCard.java
  src/main/java/wanted/ui/LoanListPanel.java
  src/main/java/wanted/ui/MainWindow.java
  src/main/java/wanted/ui/StatusBarFooter.java
  src/main/resources/images/ledger.png
  src/main/resources/view/LoanListCard.fxml
  src/main/resources/view/LoanListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/wanted/commons/util/AppUtilTest.java
Labels: priority.High

#77 Restructure loan model
  src/main/java/wanted/commons/core/datatypes/MoneyInt.java
  src/main/java/wanted/logic/Messages.java
  src/main/java/wanted/logic/commands/EditCommand.java
  src/main/java/wanted/logic/commands/RepayCommand.java
  src/main/java/wanted/logic/parser/AddCommandParser.java
  src/main/java/wanted/model/loan/Amount.java
  src/main/java/wanted/model/loan/Loan.java
  src/main/java/wanted/model/util/SampleDataUtil.java
  src/main/java/wanted/storage/JsonAdaptedLoan.java
  src/main/java/wanted/ui/LoanCard.java
  src/test/data/JsonSerializableLoanBookTest/invalidPersonLoanBook.json
  src/test/java/wanted/commons/core/datatypes/MoneyIntTest.java
  src/test/java/wanted/logic/commands/RepayCommandTest.java
  src/test/java/wanted/logic/parser/AddCommandParserTest.java
  src/test/java/wanted/logic/parser/AddressBookParserTest.java
  src/test/java/wanted/model/loan/AmountTest.java
  src/test/java/wanted/model/loan/LoanTest.java
  src/test/java/wanted/storage/JsonAdaptedLoanTest.java
  src/test/java/wanted/testutil/EditPersonDescriptorBuilder.java
  src/test/java/wanted/testutil/PersonBuilder.java
  src/test/java/wanted/testutil/PersonUtil.java
Labels: priority.High

#79 Style GUI
  src/main/java/wanted/ui/LoanCard.java
  src/main/java/wanted/ui/UiManager.java
  src/main/resources/fonts/SpecialElite-Regular.ttf
  src/main/resources/fonts/WantedM54.ttf
  src/main/resources/images/WantedList.png
  src/main/resources/images/address_book_32.png
  src/main/resources/images/blood_splatter_background.png
  src/main/resources/images/calendar.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/wanted/commons/util/AppUtilTest.java
Labels: type.Enhancement, priority.Medium

#83 Add sort command
  src/main/java/wanted/logic/commands/SortCommand.java
  src/main/java/wanted/logic/parser/AddressBookParser.java
  src/main/java/wanted/logic/parser/SortCommandParser.java
  src/test/java/wanted/logic/commands/SortCommandTest.java
Labels: type.Task, priority.High

#108 Update Model UML class diagram
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Documentation
