Repository AY2425S2-CS2103T-F11-4/tp, pull requests merged in 2025-04, with the labels that each got.

#110 Start updating user guide
  docs/UserGuide.md
Labels: type.Documentation

#116 Cleanup AB3 references
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/team/johndoe.md
  src/main/java/wanted/MainApp.java
  src/main/java/wanted/logic/Logic.java
  src/main/java/wanted/logic/commands/AddCommand.java
  src/main/java/wanted/logic/commands/ClearCommand.java
  src/main/java/wanted/logic/commands/DeleteCommand.java
  src/main/java/wanted/logic/commands/EditCommand.java
  src/main/java/wanted/logic/commands/FindCommand.java
  src/main/java/wanted/logic/commands/ListCommand.java
  src/main/java/wanted/model/LoanBook.java
  src/main/java/wanted/model/Model.java
  src/main/java/wanted/model/ModelManager.java
  src/main/java/wanted/model/ReadOnlyLoanBook.java
  src/main/java/wanted/model/loan/Address.java
  src/main/java/wanted/model/loan/Email.java
  src/main/java/wanted/model/loan/Loan.java
  src/main/java/wanted/model/loan/Name.java
  src/main/java/wanted/model/loan/Phone.java
  src/main/java/wanted/model/tag/Tag.java
  src/main/java/wanted/storage/JsonLoanBookStorage.java
  src/main/java/wanted/storage/JsonSerializableLoanBook.java
  src/main/java/wanted/storage/LoanBookStorage.java
  src/main/java/wanted/storage/Storage.java
  src/main/java/wanted/storage/StorageManager.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/wanted/logic/LogicManagerTest.java
  src/test/java/wanted/logic/commands/AddCommandTest.java
  src/test/java/wanted/logic/commands/CommandTestUtil.java
  src/test/java/wanted/logic/commands/DeleteCommandTest.java
  src/test/java/wanted/logic/commands/EditCommandTest.java
  src/test/java/wanted/model/ModelManagerTest.java
  src/test/java/wanted/storage/JsonLoanBookStorageTest.java
  src/test/java/wanted/storage/JsonSerializableLoanBookTest.java
  src/test/java/wanted/storage/StorageManagerTest.java
Labels: type.Task, priority.Low

#134 Re-enable and add phone command
  src/main/java/wanted/logic/commands/EditCommand.java
  src/main/java/wanted/logic/commands/PhoneCommand.java
  src/main/java/wanted/logic/parser/AddCommandParser.java
  src/main/java/wanted/logic/parser/LoanBookParser.java
  src/main/java/wanted/logic/parser/PhoneCommandParser.java
  src/main/java/wanted/model/loan/Loan.java
  src/main/java/wanted/model/loan/Phone.java
  src/main/java/wanted/model/loan/exceptions/PhoneUnchangedException.java
  src/main/java/wanted/storage/JsonAdaptedLoan.java
  src/main/java/wanted/ui/LoanCard.java
  src/main/resources/view/LoanListCard.fxml
  src/test/java/wanted/logic/commands/PhoneCommandTest.java
  src/test/java/wanted/storage/JsonAdaptedLoanTest.java
Labels: priority.High

#139 Update command summary table
  docs/UserGuide.md
Labels: type.Documentation, priority.Medium

#142 Add VBox to show history
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/wanted/logic/parser/LoanBookParser.java
  src/main/java/wanted/ui/LoanCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LoanListCard.fxml
Labels: type.Enhancement, priority.Medium

#123 Update usecases
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/test/java/wanted/logic/parser/LoanBookParserTest.java
Labels: type.Documentation

#140 Add test case for phone command
  src/main/java/wanted/logic/commands/PhoneCommand.java
  src/main/java/wanted/model/loan/Phone.java
  src/test/java/wanted/logic/commands/CommandTestUtil.java
  src/test/java/wanted/logic/commands/PhoneCommandTest.java
  src/test/java/wanted/logic/parser/LoanBookParserTest.java
  src/test/java/wanted/logic/parser/PhoneCommandParserTest.java
Labels: type.Task, priority.High

#131 Add find command
  src/main/java/wanted/logic/Messages.java
  src/main/java/wanted/logic/commands/FindCommand.java
  src/main/java/wanted/logic/commands/exceptions/CommandException.java
  src/main/java/wanted/model/loan/NameContainsKeywordsPredicate.java
  src/test/java/wanted/logic/commands/FindCommandTest.java
  src/test/java/wanted/logic/parser/FindCommandParserTest.java
  src/test/java/wanted/logic/parser/LoanBookParserTest.java
Labels: type.Enhancement, priority.High

#167 Update UserGuide.md about phone command
  docs/UserGuide.md
Labels: type.Documentation, priority.Medium

#169 Update developer guide with manual testing instructions
  docs/DeveloperGuide.md
Labels: type.Documentation, priority.High

#242 Update UI background and fonts
  src/main/java/wanted/logic/commands/FindCommand.java
  src/main/java/wanted/ui/LoanCard.java
  src/main/resources/images/blood_splatter_background.png
  src/main/resources/images/bloody.png
  src/main/resources/images/papyrus.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LoanListCard.fxml
Labels: UI

#246 Add total loaned amount and styled name to be larger
  src/main/java/wanted/ui/LoanCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LoanListCard.fxml
Labels: UI

#244 Add list command's feature
  src/main/java/wanted/logic/commands/ListCommand.java
  src/main/java/wanted/logic/commands/PhoneCommand.java
  src/main/java/wanted/logic/parser/PhoneCommandParser.java
  src/test/java/wanted/logic/commands/ListCommandTest.java
Labels: type.Task, priority.High

#253 Update find, list, sort and delete + change outdated screenshots
  docs/UserGuide.md
  docs/images/findjo.png
Labels: type.Documentation
